apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-con
          image: busybox:1.28
          command: [ 'sh', '-c', 'echo "Hello, World!" > /init/index.html' ]
          volumeMounts:
            - name: workdir
              mountPath: /init
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: workdir
              mountPath: /homework
          lifecycle:
            preStop:
              exec:
                command: [ "rm", "-f", "/homework/index.html" ]
          readinessProbe:
            exec:
              command:
                - cat
                - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 5
      nodeSelector:
        homework: "true"
      volumes:
        - name: workdir
          emptyDir: { }